CONF=pi
CONFLIST=pi picpu pif picpuf

loadaddr=0x80008000

objtype=arm
</$objtype/mkfile
p=9

nix:V:	$p$CONF

<| awk -f ../mk/parse $CONF
<../mk/bootmkfile
<../mk/portmkfile

OBJ=$MACH $CONF.root.$O $DEVS $PORT

# HFILES=

9:V: $p$CONF s$p$CONF

$p$CONF:DQ:	$CONF.c $OBJ $LIB mkfile
	$CC $CFLAGS '-DKERNDATE='`{date -n} $CONF.c
	echo '# linking raw kernel'
	sleep 1				# avoid relinking later
	$LD -l -o $target -H6 -R4096 -T$loadaddr $OBJ $CONF.$O $LIB

s$p$CONF:DQ:	$CONF.$O $OBJ $LIB
	echo '# linking kernel with symbols'
	sleep 1				# avoid relinking later
	$LD -l -o $target -R4096 -T$loadaddr $OBJ $CONF.$O $LIB
	size $target

install:V:	$p$CONF
	cp $p$CONF /$objtype/

installall:V:
	for(CONF in $CONFLIST)
		mk 'CONF='$CONF install

$OBJ: $HFILES

main.$O:	init.h

init.out:D:	init9.$O initcode.$O /$objtype/lib/libc.a
	$LD -l -R1 -s -o init.out init9.$O initcode.$O -lc
