</$objtype/mkfile

TARG=\
	exsort\
	format\
	iops\
	kfscmd\
	mbr\
	mkext\
	mkfs\
	mkfsconf\
	mknvrsafe\
	partfs\

SCRIPTS=\
	mkcpuboot\
	mkfsboot\

DIRS=\
	dlmicrocode\
	9660\
	kfs\
	prep\
	smart\

OFILES=

BIN=/$objtype/bin/disk

UPDATE=\
	mkfile\
	${TARG:%=%.c}\
	/sys/man/8/prep\
	/sys/man/8/mkfs\
	${TARG:%=/386/bin/disk/%}\

</sys/src/cmd/mkmany

all:V:	all-kfs

install:V:	install-kfs ksync scripts

clean:V:	clean-kfs

nuke:V:		nuke-kfs

installall:V:	installall-kfs  scripts

%-kfs:V:
	for(i in $DIRS) @{
		cd $i
		mk $MKFLAGS $stem
	}

scripts:V: $BIN/$SCRIPTS

$BIN/$SCRIPTS:	
	cp $SCRIPTS $BIN

ksync:
	touch $BIN/ksync

$O.format: /$objtype/lib/libdisk.a
